In [1]:
import pandas as pd
import numpy as np
import sklearn as skl
import matplotlib.pyplot as plt
import pickle as pk
import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score, precision_score, f1_score
from sklearn.metrics import confusion_matrix
# from sklearn.metrics import plot_confusion_matrix



In [2]:
X = pd.read_csv("data_preprocessed_python/eda_data.csv")
Y = pd.read_csv("data_preprocessed_python/eda_labels.csv")
# print(X)
print(np.mean(Y))

Unnamed: 0     19.500000
Arousal         5.156711
AVG_Arousal     4.977347
STD_Arousal     1.832603
dtype: float64


In [3]:
print(X.eda_raw[0])

[-637.8723148573772, -615.5655798498192, -615.5655798498192, -615.5655798498192, -611.1039167713607, -602.1802745076711, -602.1802745076711, -602.1802745076711, -602.1802745076711, -584.3317254485446, -584.3317254485446, -584.3317254485446, -584.3317254485446, -566.4814901479986, -566.4814901479986, -566.4814901479986, -566.4814901479986, -553.0927069329191, -553.0927069329191, -553.0927069329191, -553.0927069329191, -544.1663243813091, -544.1663243813091, -544.1663243813091, -539.7029749717913, -526.3122941637994, -526.3122941637994, -526.3122941637994, -526.3122941637994, -517.3846464381204, -517.3846464381204, -517.3846464381204, -517.3846464381204, -508.4565769280889, -508.4565769280889, -508.4565769280889, -508.4565769280889, -499.52808560361154, -499.52808560361154, -499.52808560361154, -495.06368175172247, -486.13455764972605, -486.13455764972605, -486.13455764972605, -486.13455764972605, -486.13455764972605, -486.13455764972605, -486.13455764972605, -486.13455764972605, -477.20

In [4]:
X.columns

Index(['Unnamed: 0', 'eda_filtered', 'eda_raw', 'kurt', 'max_amp', 'max_diff',
       'max_eda', 'mean_amp', 'mean_eda', 'median_eda', 'min_eda', 'num_peaks',
       'onsets', 'peaks', 'rise_time', 'skewness', 'std_dev', 'variance'],
      dtype='object')

In [5]:
X.rename(columns={"Unnamed: 0":"video_num"}, inplace=True)
Y.rename(columns={"Unnamed: 0":"video_num"}, inplace=True)
X.columns
Y.columns

Index(['video_num', 'Arousal', 'AVG_Arousal', 'STD_Arousal'], dtype='object')

In [6]:
Y_label = pd.DataFrame((Y['Arousal'])) #.astype(int)
# Y_label['AVG_Arousal'] = np.where((Y_label['AVG_Arousal'] < 6.0), np.rint(Y_label['AVG_Arousal']), np.ceil(Y_label['AVG_Arousal']))
# Y_label_avg = pd.DataFrame(Y['AVG_Arousal'])
Y_label
X_feature = X.drop(columns=['eda_raw','video_num','eda_filtered','onsets','peaks','variance','mean_eda'])
X_features = X_feature[X_feature.notnull().all(axis=1)] #dropna(inplace=True)
# X_features = np.array(X_features['std_dev']).reshape(-1,1)
Y_labels = Y_label[X_feature.notnull().all(axis=1)]
# Y_labels['AVG_Arousal'] = Y_labels['AVG_Arousal'].astype(int)
# Y_labels_ex = Y_labels[(Y_labels['Arousal'] <= 3.0) | (Y_labels['Arousal'] >= 6.0)]
Y_labels['classes'] = np.where((Y_labels['Arousal'] <= 3.0), -1, (np.where((Y_labels['Arousal'] <= 6.0), 0, 1)))

# X_features = X_features[Y_labels.classes != 0]
# Y_labels = Y_labels[Y_labels.classes != 0]

print(len(Y_labels[Y_labels.classes == -1]))
print(len(Y_labels[Y_labels.classes == 0]))
print(len(Y_labels[Y_labels.classes == 1]))


# Y_labels_ex.drop(columns=['Arousal'], inplace=True)
# X_features_ex = X_features[(Y_labels['Arousal'] <= 3.0) | (Y_labels['Arousal'] >= 6.0)]
# X_features_ex
# Y_labels_ex

217
513
511


/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_features, Y_labels['classes'], test_size=0.30, random_state=10)
# X_train.join(y_train)
print(X_train.head())

print("\n testing data: \n")
print(len(y_test[y_test==-1]))
print(len(y_test[y_test==0]))
print(len(y_test[y_test==1]))

print("\n training data: \n")
print(len(y_train[y_train==-1]))
print(len(y_train[y_train==0]))
print(len(y_train[y_train==1]))
print(X_train.columns)

         kurt       max_amp      max_diff      max_eda     mean_amp  \
245 -1.031018   5295.989552   9542.340425  9050.925379  5415.250795   
944 -0.018622    232.161011    462.925122   329.674332   129.727947   
732 -0.777564  29571.467437  45804.222036  4967.198328 -3909.582845   
276 -1.414127   1628.542301   3210.612545   622.574083  -989.548698   
361 -0.805845  10561.714076  20532.683881  7282.097857 -1054.043972   

       median_eda       min_eda  num_peaks   rise_time  skewness       std_dev  
245   4799.250278   -491.415046          5  115.400000 -0.177598   2534.439686  
944    104.149898   -133.250790         36  106.888889  0.029346     80.272181  
732 -10665.424454 -40837.023708          6  289.500000 -0.477261  12254.660106  
276  -1005.714208  -2588.038463         12  233.833333 -0.134769    966.895409  
361  -2711.509086 -13250.586024          3  562.000000 -0.026996   5239.229506  

 testing data: 

64
144
165

 training data: 

153
369
346
Index(['kurt', 'max_amp', '

In [8]:
#with feature scaling

scalar = StandardScaler()
scalar.fit(X_train,y_train)
scaled_X_train = scalar.transform(X_train)
scaled_X_test = scalar.transform(X_test)
joblib.dump(scalar, 'eda_scaler.pkl', protocol=2)
# fs_log_reg = LogisticRegression(C=10).fit(scaled_X_train,y_train)

# #training data accuracy 
# #removing rise time causes much less units to be classified is low arousal
# print("Training Data: \n")
# fs_y_pred = fs_log_reg.predict(scaled_X_train)
# R = recall_score(y_train,fs_y_pred,average=None)
# P = precision_score(y_train,fs_y_pred,average=None)
# F1 = f1_score(y_train,fs_y_pred,average=None)
# print("Recall: "+str(R),"Precision: "+str(P), "F1 score: "+str(F1))
# print(fs_log_reg.coef_, fs_log_reg.score(scaled_X_train,y_train))
# # print(X_features.columns)

# matrix = confusion_matrix(fs_y_pred, y_train)

# print(matrix)

# #testing data accuracy 
# print("\n Testing Data: \n")
# fs_y_pred = fs_log_reg.predict(scaled_X_test)
# R = recall_score(y_test,fs_y_pred,average=None)
# P = precision_score(y_test,fs_y_pred,average=None)
# F1 = f1_score(y_test,fs_y_pred,average=None)
# print("Recall: "+str(R),"Precision: "+str(P), "F1 score: "+str(F1))
# print(fs_log_reg.coef_, fs_log_reg.score(scaled_X_test,y_test))
# # print(X_features.columns)

# confusion_matrix(fs_y_pred, y_test)



['eda_scaler.pkl']

In [9]:
from sklearn.neural_network import MLPClassifier

nodes = [i for i in range(1,len(X_train.columns)*2)]
layers = [i for i in range(1,len(X_train.columns)*2)]

outputs = pd.DataFrame(columns=['layers','nodes','test_acc','train_acc', 'test_precision','test_recall','test_F1', 'train_precision','train_recall','train_F1'])

lowest_acc_diff = 1.0
lowest_acc_diff_nodes = 1
lowest_acc_diff_layers = 1

best_train_acc = 0.0
best_train_nodes = 1
best_train_layers = 1

best_test_acc = 0.0
best_test_nodes = 1
best_test_layers = 1

for i in range(len(layers)):
    for j in range(len(nodes)):
#         print("layers: "+str(layers[i])+", nodes: "+str(nodes[j])+" \n")
        clf = MLPClassifier(solver='lbfgs',activation='tanh', learning_rate='invscaling', learning_rate_init = 0.0001,hidden_layer_sizes=(nodes[j], layers[i]), random_state=12)
        clf.fit(scaled_X_train, y_train)
        
#         print("training data: \n")
        preds = clf.predict(scaled_X_train)
        trn_acc = clf.score(scaled_X_train, y_train)
        R_train = recall_score(y_train,preds,average=None)
        P_train = precision_score(y_train,preds,average=None)
        print(set(y_train)-set(preds))
        F1_train = f1_score(y_train,preds,average=None)
        if trn_acc > best_train_acc:
            best_train_acc = trn_acc
            best_train_nodes = nodes[j]
            best_train_layers = layers[i]
#         print(confusion_matrix(preds, y_train))

#         print("\n testing data: \n")
        preds = clf.predict(scaled_X_test)
        tst_acc = clf.score(scaled_X_test, y_test)
        R_test = recall_score(y_test,preds,average=None)
        P_test = precision_score(y_test,preds,average=None)
        print(set(y_test)-set(preds))
        F1_test = f1_score(y_test,preds,average=None)
        if tst_acc > best_test_acc:
            best_test_acc = tst_acc
            best_test_nodes = nodes[j]
            best_test_layers = layers[i]
            
#         if abs(trn_acc-tst_acc) < lowest_acc_diff:
#             lowest_acc_diff = abs(trn_acc-tst_acc)
#             lowest_acc_diff_nodes = nodes[j]
#             lowest_acc_diff_layers = layers[i]
        
        outputs = outputs.append(pd.DataFrame([[layers[i],nodes[j],tst_acc,trn_acc,P_test,R_test,F1_test,P_train,R_train,F1_train]], columns=['layers','nodes','test_acc','train_acc', 'test_precision','test_recall','test_F1', 'train_precision','train_recall','train_F1']))
#         print(outputs.head)
#         print(confusion_matrix(preds, y_test))
        
#         print("Train accuracy: "+str(trn_acc)+ ", Test accuracy: "+ str(tst_acc)+ " \n")
    
# best accuracy on training data


# lowest difference in accuracy between training and testing data sets
# print("\n lowest difference between accuries was "+str(lowest_acc_diff) +" using "+str( lowest_acc_diff_layers)+" layers with "+str(lowest_acc_diff_nodes)+ " nodes each")

# clf = MLPClassifier(solver='lbfgs',activation='tanh',hidden_layer_sizes=(lowest_acc_diff_nodes, lowest_acc_diff_layers), random_state=42)
# clf.fit(scaled_X_train, y_train)

# preds = clf.predict(scaled_X_train)
# print(confusion_matrix(y_train, preds))
# R = recall_score(y_train,preds,average=None)
# P = precision_score(y_train,preds,average=None)
# F1 = f1_score(y_train,preds,average=None)
# print("Training Recall: "+str(R),"Training Precision: "+str(P), "Training F1 score: "+str(F1))
# print("Training accuracy is "+str(clf.score(scaled_X_train, y_train)) +" \n")

# preds = clf.predict(scaled_X_test)
# print(confusion_matrix(y_test, preds))
# R = recall_score(y_test,preds,average=None)
# P = precision_score(y_test,preds,average=None)
# F1 = f1_score(y_test,preds,average=None)
# print("Testing Recall: "+str(R),"Testing Precision: "+str(P), "Testing F1 score: "+str(F1))



/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


{1, -1}
{1, -1}
set()
set()
set()
set()
{-1}
{-1}


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py

{-1}
{-1}
set()
set()
{-1}
{-1}


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py

{1}
{1}
{1}
{1}


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


set()
set()
set()
set()
set()
{1}
{-1}
{-1}


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py

set()
set()
set()
set()
{1}
{1}


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


set()
set()
{-1}
{-1}


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py

{-1}
{-1}
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
{1}
{1}


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
{-1}
{-1}


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
{-1}
{-1}


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set(

/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
{-1}


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
{-1}
{-1}


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
{-1}
{-1}


/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set()
set(

In [10]:
# print("best training accuracy is "+str(best_train_acc)+" using "+ str(best_train_layers)+" layers with "+ str(best_train_nodes) + " nodes each")
# np.set_printoptions(precision=2)
class_names = ['low', 'mod', 'hi']

clf = MLPClassifier(solver='lbfgs',activation='tanh',learning_rate='invscaling', hidden_layer_sizes=(16, 21), random_state=12)
clf.fit(scaled_X_train, y_train)
preds = clf.predict(scaled_X_train)

mtx = confusion_matrix(y_train, preds).astype('float')
for i in range(len(mtx)):
#     row = mtx[i]
    mtx[i] = (mtx[i])/np.sum(mtx[i])

print(mtx)
print(confusion_matrix(y_train, preds))

joblib.dump(clf, 'nn_eda_model.pkl', protocol=2)

R = recall_score(y_train,preds,average=None)
P = precision_score(y_train,preds,average=None)
F1 = f1_score(y_train,preds,average=None)
print("Training Recall: "+str(R),"Training Precision: "+str(P), "Training F1 score: "+str(F1))
print(clf.score(scaled_X_train,y_train))


# best testing accuracy

preds = clf.predict(scaled_X_test)
# print(confusion_matrix(y_test, preds))
mtx = confusion_matrix(y_test, preds).astype('float')
for i in range(len(mtx)):
#     row = mtx[i]
    mtx[i] = (mtx[i])/np.sum(mtx[i])

print(mtx)
print(confusion_matrix(y_test, preds))


R = recall_score(y_test,preds,average=None)
P = precision_score(y_test,preds,average=None)
F1 = f1_score(y_test,preds,average=None)
print("Testing Recall: "+str(R),"Testing Precision: "+str(P), "Testing F1 score: "+str(F1))
print("Testing accuracy is "+str(clf.score(scaled_X_test, y_test))+" \n")


# # best accuracy on testing data
# print("best testing accuracy is "+str(best_test_acc)+" using "+ str(best_test_layers)+" layers with "+ str(best_test_nodes) + " nodes each")
# clf = MLPClassifier(solver='lbfgs',activation='tanh', learning_rate='invscaling', hidden_layer_sizes=(best_test_nodes, best_test_layers), random_state=42)
# clf.fit(scaled_X_train, y_train)

# preds = clf.predict(scaled_X_train)
# print(confusion_matrix(y_train, preds))
# R = recall_score(y_train,preds,average=None)
# P = precision_score(y_train,preds,average=None)
# F1 = f1_score(y_train,preds,average=None)
# print("Training Recall: "+str(R),"Training Precision: "+str(P), "Training F1 score: "+str(F1))
# print("Training accuracy is "+str(clf.score(scaled_X_train, y_train)) +" \n")

# preds = clf.predict(scaled_X_test)
# print(confusion_matrix(y_test, preds))
# R = recall_score(y_test,preds,average=None)
# P = precision_score(y_test,preds,average=None)
# F1 = f1_score(y_test,preds,average=None)
# print("Testing Recall: "+str(R),"Testing Precision: "+str(P), "Testing F1 score: "+str(F1))

[[0.66666667 0.16993464 0.16339869]
 [0.04336043 0.83468835 0.12195122]
 [0.05202312 0.15895954 0.78901734]]
[[102  26  25]
 [ 16 308  45]
 [ 18  55 273]]
Training Recall: [0.66666667 0.83468835 0.78901734] Training Precision: [0.75       0.79177378 0.79591837] Training F1 score: [0.70588235 0.81266491 0.79245283]
0.7868663594470046
[[0.34375    0.375      0.28125   ]
 [0.1875     0.4375     0.375     ]
 [0.2        0.35757576 0.44242424]]
[[22 24 18]
 [27 63 54]
 [33 59 73]]
Testing Recall: [0.34375    0.4375     0.44242424] Testing Precision: [0.26829268 0.43150685 0.50344828] Testing F1 score: [0.30136986 0.43448276 0.47096774]
Testing accuracy is 0.42359249329758714 



In [11]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
outputs.sort_values(by=['train_acc','test_acc'], ascending=False)

layers nodes  test_acc  train_acc  \
0     17    17  0.372654   0.868664   
0     21    20  0.404826   0.853687   
0     14    21  0.428954   0.852535   
0     21    19  0.436997   0.844470   
0     19    20  0.410188   0.844470   
0     20    15  0.423592   0.837558   
0     18    21  0.407507   0.836406   
0     19    19  0.426273   0.835253   
0     18    19  0.402145   0.834101   
0     20    19  0.418231   0.832949   
0     20    18  0.364611   0.830645   
0     16    21  0.410188   0.826037   
0     18    20  0.418231   0.819124   
0     18    18  0.453083   0.816820   
0     21    21  0.436997   0.816820   
0     15    20  0.399464   0.813364   
0     19    18  0.423592   0.812212   
0     12    21  0.372654   0.812212   
0     16    19  0.439678   0.811060   
0     14    20  0.434316   0.808756   
0     13    20  0.445040   0.807604   
0     20    21  0.431635   0.807604   
0     17    21  0.423592   0.806452   
0     20    16  0.394102   0.806452   
0     20    20  0.436997   0.805300   
0     12    20  0.386059   0.804147   
0     21    18  0.369973   0.804147   
0     19    21  0.375335   0.800691   
0     13    19  0.423592   0.799539   
0     14    18  0.407507   0.798387   
0     17    18  0.426273   0.797235   
0     20    17  0.436997   0.796083   
0     13    21  0.436997   0.793779   
0     17    20  0.450402   0.791475   
0     21    13  0.466488   0.790323   
0     12    19  0.383378   0.790323   
0     16    14  0.418231   0.789171   
0     11    21  0.391421   0.789171   
0     14    19  0.372654   0.789171   
0     16    20  0.442359   0.788018   
0     21    16  0.423592   0.786866   
0     15    19  0.418231   0.785714   
0     15    21  0.418231   0.785714   
0     16    18  0.447721   0.783410   
0     13    18  0.434316   0.783410   
0     17    14  0.434316   0.783410   
0     18    17  0.450402   0.781106   
0     10    20  0.426273   0.779954   
0      8    21  0.412869   0.778802   
0     19    14  0.431635   0.777650   
0     19    13  0.412869   0.775346   
0     17    16  0.415550   0.774194   
0     16    17  0.447721   0.773041   
0     11    20  0.434316   0.771889   
0     11    18  0.418231   0.771889   
0     21    17  0.420912   0.770737   
0     17    15  0.450402   0.768433   
0     21    11  0.420912   0.768433   
0     13    15  0.402145   0.767281   
0     19    15  0.378016   0.767281   
0     19    12  0.450402   0.766129   
0     21    15  0.415550   0.766129   
0     15    15  0.447721   0.763825   
0     15    16  0.402145   0.763825   
0     14    16  0.445040   0.762673   
0     10    19  0.428954   0.762673   
0     11    19  0.418231   0.762673   
0     15    17  0.415550   0.761521   
0     20    14  0.447721   0.760369   
0     12    17  0.439678   0.760369   
0     18    14  0.431635   0.760369   
0     12    16  0.428954   0.759217   
0     19    16  0.426273   0.759217   
0     20    13  0.410188   0.759217   
0     17    19  0.372654   0.759217   
0     15    18  0.410188   0.758065   
0     12    18  0.461126   0.756912   
0     17    13  0.383378   0.755760   
0     16    16  0.445040   0.754608   
0     18    16  0.426273   0.754608   
0      9    19  0.453083   0.753456   
0     10    17  0.445040   0.752304   
0     19    17  0.439678   0.751152   
0     16    15  0.388740   0.751152   
0     13    17  0.426273   0.750000   
0     12    14  0.426273   0.748848   
0     14    17  0.407507   0.747696   
0     10    18  0.439678   0.746544   
0     15    13  0.418231   0.746544   
0      9    21  0.439678   0.744240   
0     20    11  0.426273   0.744240   
0      9    20  0.469169   0.740783   
0     18    13  0.434316   0.740783   
0     12    15  0.431635   0.740783   
0     16    12  0.501340   0.738479   
0     15    14  0.386059   0.738479   
0     18    11  0.383378   0.738479   
0      9    18  0.453083   0.735023   
0     20    12  0.407507   0.735023   
0      7    20  0.447721   0.733871   
0     18    15  0.396783   0.733871   
0     13    14  0.380697

In [12]:

degrees = [1, 2, 3, 4, 5, 6, 7, 8, 9]

def PolyLogRegression(degree, X_train, y_train, X_test, y_test):
    poly = PolynomialFeatures(degree)
    
    #first use training data to fit features
    poly.fit(X_train, y_train)
    #transform training data to create new features
    tr_X_train = poly.transform(X_train)
    #transform testing data to create new features
    tr_X_test = poly.transform(X_test)

    #logistic regression
    clf = LogisticRegression(C=10).fit(tr_X_train, y_train)
#     print(poly.get_feature_names(X_train.columns))
    print(confusion_matrix(y_train, clf.predict(tr_X_train)))
    return clf.score(tr_X_train,y_train)

# for d in degrees:
#     print(d, PolyLogRegression(d, scaled_X_train, y_train, scaled_X_test, y_test))

In [13]:
# from sklearn import linear_model # Using sklearn Perceptron classifier
# from sklearn import ensemble # Using RandomForest classifier
# from sklearn import neighbors # Using nearest neighbors classifier
# from sklearn.model_selection import cross_val_score
# learners = {'Perceptron': linear_model.Perceptron(max_iter=10), 'RandomForest': ensemble.RandomForestClassifier(), 'kNN': neighbors.KNeighborsClassifier(), 'LogisticRegression': LogisticRegression() }

# for classifierName in learners:
#     score = cross_val_score(learners[classifierName],scaled_X_train, y_train, cv=5)
#     print('Accuracy of ' + classifierName + ':\t' + str((score)))